### ISSUE TITLE
Jetty website + documentation URLs are redirecting to "Archived Eclipse Projects" page

### ISSUE THREAD

**Issue by boughtonp** [eclipse/jetty.website#3]
https://www.eclipse.org/jetty is redirecting to https://www.eclipse.org/projects/archives.php

Likewise for documentation links.

**Comment by jmcc0nn3ll** [comment]
Wow, something odd going on here.  I suspect it is something at eclipse, @WalkerWatch nothing odd in the last release update right?

**Comment by jmcc0nn3ll** [comment]
Published content looks correct, gotta be something at Eclipse.

https://git.eclipse.org/c/www.eclipse.org/jetty.git/tree/

**Comment by jmcc0nn3ll** [comment]
opened a bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=562719

**Comment by jmcc0nn3ll** [comment]
fixed, thanks for the heads up!  it was a configuration mistake at eclipse with a freshly archived project that shared a similar name
