### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by waynebeaton** [eclipse/jetty.website#4]
From the EMO Inbox:

> All of the https://www.eclipse.org/jetty/documentation/current/ links are broken. I wonder if it has to do with you adding the v10 beta.

It looks more to me like a relatively small number of links are broken (eg. references to JSR-318 and JOTM). My link checker found 13 404s (at least many of them are example URLs that probably shouldn't be links).

**Comment by WalkerWatch** [comment]
@waynebeaton I will take a look into this. Thanks for the insight. Happen to have the list of 13 your tooling found? I will hunt for others.

**Comment by jmcc0nn3ll** [comment]
FYI we'll we deploying new site soon as well and will have to work with webmaster to get a mess of things redirected

**Comment by waynebeaton** [comment]
I'm using something called "Check My Links". Apparently the tool doesn't have an export function. I guess that I need to find a different tool (I've used wget to do this in the past).

The following links are reporting as 404:

* https://www.eclipse.org/jetty/documentation/current/jcp.org/en/jsr/detail?id=318
* http://jotm.ow2.org/xwiki/bin/view/Main/WebHome
* https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-alpn/jetty-alpn-conscrypt-server/src/test/java/org/eclipse/jetty/alpn/conscrypt/server/ConscryptHTTP2Server.java
* https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-alpn/jetty-alpn-conscrypt-client/src/test/java/org/eclipse/jetty/alpn/java/client/ConscryptHTTP2Client.java
* http://graphviz.org/content/command-line-invocation
* https://blogs.oracle.com/lmalventosa/entry/jmx_authentication_authorization
* https://www.eclipse.org/jetty/documentation/current/configuring-webapps.html#webapp-context-attributes
* https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/tests/test-webapps/test-jetty-webapp/src/main/config/etc/test-realm.xml
* https://repo1.maven.org/maven2/javax/websocket/websocket-api
* https://admin.fedoraproject.org/pkgdb/acls/name/jetty
* https://www.eclipse.org/jetty/documentation/current/%7BGITBROWSURL%7D/jetty-webapp/src/main/config/etc/webdefault.xml

There's a bunch of links to things like http://www.other.com/other which are obviously not intended to be links.

* https://example.com/j_security_check

Curiously, my link checker is reporting a bunch of "localhost" links as valid. I probably need a better link checker...

You may consider escaping the example links so that the HTML generator doesn't automatically make them linkable.

**Comment by WalkerWatch** [comment]
@waynebeaton I ran some more verbose tooling and found a number of issues, though most are redirects that will soon be remedied or placeholder URLs that are not real. In the meantime I am going to address the ones you listed and go from there after that.

**Comment by sirmspencer** [comment]
Here are two more 
https://www.eclipse.org/jetty/documentation/current/webdefault-xml.html
https://www.eclipse.org/jetty/documentation/current/quickstart-config-what.html

I ran into 4 or 5 yesterday.  I know at least one that was dead yesterday was working last week when I was doing the same research.

These links lead to a styled 404 not found page.

**Comment by kevloral** [comment]
I have found some more Jetty v9 documentation links that are broken in https://www.eclipse.org/jetty/documentation.php:

* https://www.eclipse.org/jetty/documentation/jetty-9/index.php -> https://www.eclipse.org/jetty/documentation/jetty-9/index.html
* https://www.eclipse.org/jetty/javadoc/9.4/index.html?overview-summary.html -> https://www.eclipse.org/jetty/javadoc/9/index.html?overview-summary.html

**Comment by jmcc0nn3ll** [comment]
N/A
